phina.globalize();

// Const
var SCREEN_WIDTH = 640;
var SCREEN_HEIGHT = 960;
var NODE_WIDTH = 80;
var NODE_HEIGHT = 40;
var NODE_LENGTH = 51;
var AREA_LENGTH = 3;
//var AREA_DEF_POS = Vector2(0 , 0);
//var NODE_DEF_POS = Vector2(11 , 11);
//var STEP_HEIGHT = 30;
var MAP_WIDTH = NODE_WIDTH * NODE_LENGTH * AREA_LENGTH;
var MAP_HEIGHT = NODE_HEIGHT * NODE_LENGTH * AREA_LENGTH;
//var PROCESS_MARGIN = 28;
var MAINSCENE_BG_COLOR = "#2792c3"; // はなだ色

// LoadingScene
var LOADINGSCENE_BG_COLOR = "#333";
var LOADINGSCENE_GAUGE_WIDTH = 120;
var LOADINGSCENE_GAUGE_HEIGHT = 12;
var LOADINGSCENE_GAUGE_BG_COLOR = "#555";
var LOADINGSCENE_GAUGE_COLOR = "rgb(170 , 76 , 143)";
var LOADINGSCENE_GAUGE_ANIMATION_TIME = 300; //0だと自動で1000になる
var LOADINGSCENE_GAUGE_POS_X = SCREEN_WIDTH/2;
var LOADINGSCENE_GAUGE_POS_Y = SCREEN_HEIGHT/2;
var LOADINGSCENE_LABEL_TEXT = "Loading..";
var LOADINGSCENE_LABEL_COLOR = "#777";
var LOADINGSCENE_LABEL_FONT_SIZE = 25;
var LOADINGSCENE_LABEL_FONT_WEIGHT = "bold";
var LOADINGSCENE_LABEL_MARGIN_TOP = 25; //ローダーからの縦距離(px)
var LOADINGSCENE_LABEL_POS_X = SCREEN_WIDTH/2;
var LOADINGSCENE_LABEL_POS_Y = SCREEN_HEIGHT/2 + LOADINGSCENE_LABEL_MARGIN_TOP;





phina.main(function() {
  var app = GameApp({
    startLabel: 'main',
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
    assets: ASSETS,
  });
  if(!phina.isMobile()) app.enableStats();
  app.run(); // LoadingScene → MainScene
});
