//
//
// Main.js
// 2017 @auther piteredo
// This Program is MIT license.
//
//
phina.globalize();

// Const
SCREEN_WIDTH = 480; //決定させる(640*0.7 / 960*0.7)？
SCREEN_HEIGHT = 720;
SCREEN_CTR_PX_POS = Vector2(SCREEN_WIDTH, SCREEN_HEIGHT); //CameraFocusで使用
NODE_WIDTH = 80;
NODE_HEIGHT = 40;
NODE_LENGTH = 51;
AREA_LENGTH = 3;
HERO_UUID = Random.uuid(); //phina.util.Random;
AREA_DEF_POS = Vector2(1 , 1);
NODE_DEF_POS = Vector2(25 , 25);
//var STEP_HEIGHT = 30;
MAP_WIDTH = NODE_WIDTH * NODE_LENGTH * AREA_LENGTH;
MAP_HEIGHT = NODE_HEIGHT * NODE_LENGTH * AREA_LENGTH;
//PROCESS_MARGIN = 28;
MAINSCENE_BG_COLOR = "#2792c3"; // はなだ色

// LoadingScene
LOADINGSCENE_BG_COLOR = "#333";
LOADINGSCENE_GAUGE_WIDTH = 120;
LOADINGSCENE_GAUGE_HEIGHT = 12;
LOADINGSCENE_GAUGE_BG_COLOR = "#555";
LOADINGSCENE_GAUGE_COLOR = "rgb(170 , 76 , 143)";
LOADINGSCENE_GAUGE_ANIMATION_TIME = 300; //0だと自動で1000になる
LOADINGSCENE_GAUGE_POS_X = SCREEN_WIDTH/2;
LOADINGSCENE_GAUGE_POS_Y = SCREEN_HEIGHT/2;
LOADINGSCENE_LABEL_TEXT = "Loading..";
LOADINGSCENE_LABEL_COLOR = "#777";
LOADINGSCENE_LABEL_FONT_SIZE = 25;
LOADINGSCENE_LABEL_FONT_WEIGHT = "bold";
LOADINGSCENE_LABEL_MARGIN_TOP = 25; //ローダーからの縦距離(px)
LOADINGSCENE_LABEL_POS_X = SCREEN_WIDTH/2;
LOADINGSCENE_LABEL_POS_Y = SCREEN_HEIGHT/2 + LOADINGSCENE_LABEL_MARGIN_TOP;

// Map
MAP_FLOOR_LAYER_NAME = "FLOOR"; //TileMapEditorのレイヤー名に依存
MAP_COLLISION_LAYER_NAME = "COLLISION";
MAP_OBJECTS_LAYER_NAME = "OBJECT";
MAP_NPC_LAYER_NAME = "NPC";
MAP_ENEMY_LAYER_NAME = "ENEMY";

// Character
CHAR_HERO_NAME = "わたし";

// Camera
CAMERA_POS = Vector2(SCREEN_WIDTH/2 , SCREEN_HEIGHT/2);



phina.main(function() {

  var app = GameApp({
    startLabel: 'main',
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
    assets: ASSETS,
  });

  if(!phina.isMobile()) app.enableStats();

  app.run(); // LoadingScene → MainScene
});
